add haproxy config for http mode
rhcs-dashboard/ceph-dev pull request #35
Opened 2021-02-04 11:32 UTC by avanthakkar

Signed-off-by: Avan Thakkar <athakkar@redhat.com>

2021-02-10 10:08 UTC, alfonsomthd requested changes

2021-02-10 10:08 UTC, alfonsomthd commented on docker-compose.yml
> +        image: haproxy
```suggestion
        image: ${HAPROXY_IMAGE:-haproxy:latest}
```

2021-02-10 10:08 UTC, alfonsomthd commented on docker-compose.yml
> +        image: haproxy
For consistency, under ```image:```, it should be added:
```
        container_name: haproxy
        hostname: haproxy
```

Also, in ```.env.example``` it should be added:
HAPROXY_HOST_HTTP_PORT=80
HAPROXY_HOST_HTTPS_PORT=443
#HAPROXY_IMAGE=

2021-02-11 12:32 UTC, avanthakkar commented on docker-compose.yml
> +        image: haproxy
Done!

2021-02-12 07:39 UTC, avanthakkar commented
Closing it as it's already covered here https://github.com/rhcs-dashboard/ceph-dev/commit/2d20eb64fc1d619fcdff3d333754552cbdc1a6d3

2021-02-12 07:39 UTC, closed without merging